### PR TITLE
Migrate Tut to Mdoc

### PR DESCRIPTION
**Pull request by asachdeva**
This is a first cut at migrating the Tut to Mdoc

### CODE REVIEW

**Comment by gvolpe** [comment]
That NoSuchMethodError indicates a binary compatibility issue. Can you try updating Kind Projector to the latest version (it's been moved to Typelevel) and use `cross CrossVersions.full`? (or sth like that, check the docs)

**Comment by asachdeva** [comment]
Done on Kind Projector update...Mdoc errors and warning are just as I am seeing in my local environment now.  Thanks

**Comment by gvolpe** [comment]
> Done on Kind Projector update...Mdoc errors and warning are just as I am seeing in my local environment now. Thanks

Cool! Does that mean you know how to fix it? :smile:

**Comment by asachdeva** [comment]
> > Done on Kind Projector update...Mdoc errors and warning are just as I am seeing in my local environment now. Thanks
> 
> Cool! Does that mean you know how to fix it? smile

Not yet.
I am down to "not found: type F" errors or essentially mdoc (and how it works) having issues with interpreting tagless final code.  I will reach out to mdoc guys on gitter to see if they have any advice.

**Comment by gvolpe** [comment]
Aaah don't worry. This code should compile as is.

The problem is that `mdoc` doesn't compile things in the same way `tut` does. That's a bit disappointing because one would expect an easy migration.

I had a similar issue migrating `cats-tagless` recently: https://github.com/scalameta/mdoc/issues/256

It is not going to be easy to fix I'm afraid but if you're willing to put up the work, the `mdoc` guys are really helpful and can guide you through.

**Comment by asachdeva** [comment]
I will see this through.

**Comment by asachdeva** [comment]
Opened issue on mdoc as https://github.com/scalameta/mdoc/issues/259 to get advice and options on how to proceed.

**Pull request closed without merging**
